osx_image: xcode8.3

matrix:
  include:
    - os: osx
      env: TEST_FILES=BuildTest,extraMetadataTest,globTest,filesTest,ignoreTest,linux.*,windows.* NODE_VERSION=6 PUBLISH_TO_NPM=true

    - os: osx
      env: TEST_FILES=mac.* NODE_VERSION=8

    - os: osx
      env: TEST_FILES=mac.* NODE_VERSION=6

language: c

cache:
  directories:
    - node_modules
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder
    - /tmp/jest-electron-builder-tests

before_install:
  - curl -L https://dl.bintray.com/develar/bin/7za -o /tmp/7za
  - chmod +x /tmp/7za
  - curl -L https://dl.bintray.com/develar/bin/wine-2.0.7z -o /tmp/wine.7z
  - /tmp/7za x -o/usr/local/Cellar -y /tmp/wine.7z
  - brew link --overwrite gnutls libtasn1 libusb libusb-compat nettle openssl wine git-lfs gnu-tar dpkg xz
  - git-lfs pull

# fontconfig jasper libgphoto2 libicns little-cms2 sane-backends webp gd

install:
- nvm install $NODE_VERSION
- nvm use --delete-prefix $NODE_VERSION
- ln -sf $PWD/test/vendor/yarn.js /usr/local/bin/yarn
- yarn --link-duplicates --pure-lockfile
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" && "$AUTO_PUBLISH" != "false" && "$TRAVIS_TAG" == "" && "$PUBLISH_TO_NPM" == "true" ]]; then yarn add @develar/semantic-release@next --dev ; fi

script:
- yarn test

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" && "$AUTO_PUBLISH" != "false" && "$TRAVIS_TAG" == "" && "$PUBLISH_TO_NPM" == "true" ]]; then npm run semantic-release ; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"