osx_image: xcode8

matrix:
  include:
    - os: osx
      env: NODE_VERSION=6

    - os: osx
      env: TEST_FILES=osxPackagerTest,CodeSignTest NODE_VERSION=4

language: c

cache:
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache/fpm

before_install:
  - brew install --ignore-dependencies --force-bottle gnu-tar dpkg libicns graphicsmagick lzip freetype
  - brew deps --skip-optional wine | grep -v -e freetype -e libtiff -e libpng -e libtool -e libicns -e jpeg -e gmp | xargs brew install --ignore-dependencies --force-bottle
  - brew install --ignore-dependencies --force-bottle wine
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull

install:
- nvm install $NODE_VERSION
- nvm use --delete-prefix $NODE_VERSION
- if [[ "$TRAVIS_OS_NAME" == "osx" && "$NODE_VERSION" == "4" ]]; then npm install npm -g ; fi
- npm install
- npm prune

script:
- npm run test

after_success:
#- node out/cleanup.js
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" && "$AUTO_PUBLISH" != "false" ]]; then npm run semantic-release ; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"