osx_image: xcode7

dist: trusty
sudo: required

services:
  - docker

matrix:
  include:
    - os: linux
      env: CIRCLE_NODE_INDEX=0 NODE_VERSION=6

    - os: linux
      env: CIRCLE_NODE_INDEX=1 NODE_VERSION=6

    - os: osx
      env: TEST_FILES=osxPackagerTest,CodeSignTest NODE_VERSION=6

    - os: osx
      env: TEST_FILES=linuxPackagerTest,BuildTest NODE_VERSION=6

    - os: osx
      env: TEST_FILES=osxPackagerTest,CodeSignTest NODE_VERSION=4

language: c

cache:
  directories:
    - node_modules
    - test/testApp/node_modules
    - $HOME/.electron
    - $HOME/.cache/fpm

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TEST_FILES" == l* ]]; then brew install gnu-tar dpkg libicns graphicsmagick lzip; fi
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull

install:
- nvm install $NODE_VERSION
- if [[ "$TRAVIS_OS_NAME" == "osx" && "$NODE_VERSION" == "4" ]]; then npm install npm -g ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm install && npm prune ; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run test ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CIRCLE_NODE_INDEX" == "0" ]]; then docker run --rm --env-file ./test/docker-env.list -v ${PWD}:/project -v ~/.electron:/root/.electron electronuserland/electron-builder:latest /bin/bash -c "/test.sh && ./test/release.sh" ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CIRCLE_NODE_INDEX" == "1" ]]; then docker run --rm --env-file ./test/docker-env.list -v ${PWD}:/project -v ~/.electron:/root/.electron electronuserland/electron-builder:wine /bin/bash -c "/test.sh && ./test/release.sh" ; fi

after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then node out/cleanup.js && ./test/release.sh ; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"