os:
  - osx
  - linux

env:
  - NODE_VERSION=4
  - NODE_VERSION=5.8

language: ruby

cache:
  directories:
    - node_modules
    - test/testApp/node_modules
    - $HOME/.electron
    - $HOME/.npm

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar dpkg libicns graphicsmagick git-lfs; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs pull; fi
  - gem install --no-rdoc --no-ri fpm

install:
- rm -rf ~/.nvm
- git clone https://github.com/creationix/nvm.git ~/.nvm
- source ~/.nvm/nvm.sh
- nvm install $NODE_VERSION
- npm install npm -g
- npm prune
- npm install

script:
- npm run test

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" && "$AUTO_PUBLISH" != "false" ]]; then npm run semantic-release ; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"