platform:
  - x64

cache:
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\.cache\nsis'

install:
  - ps: Install-Product node 6 x64
  - npm install
  - npm prune

build: off

test_script:
  - npm run test