platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 7 x64
  - choco install -i yarn
  - refreshenv
  # unknown yarn error
  - npm install
  - npm prune

build: off

test_script:
  - npm run test