platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 6 x64
  - choco install -i yarn
  - refreshenv
  - yarn install

build: off

test_script:
  - npm run test